ERROR_CODES = {
    "PROFILE_ALREADY_EXISTS": "PROFILE_ALREADY_EXISTS",
    "USER_NOT_FOUND": "USER_NOT_FOUND",
    "DATABASE_ERROR": "DATABASE_ERROR",
    "ASSIGNMENT_CREATION_FAILED": "ASSIGNMENT_CREATION_FAILED"
}